### ISSUE TITLE
Cree la clase Receta

### ISSUE THREAD

**Issue by NikoVelazco** [NikoVelazco/repo-tpfinal-pv-2023#23]
En el paquete ar.edu.unju.fi.entity cree la clase receta.
Codifique la clase Receta con todos los atributos que se solicita en el práctico.
Cree el constructor parametrizado y el constructor por defecto. 
Cree los métodos getter y setter de la clase Receta.

**Comment by cristianortega0** [comment]
Realizado en la Rama Receta
