### ISSUE TITLE
Cree la clase Ingrediente

### ISSUE THREAD

**Issue by NikoVelazco** [NikoVelazco/repo-tpfinal-pv-2023#25]
Dentro del paquete ar.edu.unju.fi.entity cree la clase Ingrediente
Realice la codificación de la clase agregando los atributos que se solicita en el práctico.
Cree el constructor parametrizado y el constructor por defecto.
Cree los métodos getter y setter de la clase Ingrediente.

**Comment by SaraDMercado** [comment]
Terminado.
