### ISSUE TITLE
Cree las interfaces para la clase Receta

### ISSUE THREAD

**Issue by NikoVelazco** [NikoVelazco/repo-tpfinal-pv-2023#28]
En el paquete ar.edu.unju.fi.repository cree la interfaz IRecetaRepository con su codificación necesaria para el funcionamiento del proyecto.

En el paquete ar.edu.unju.fi.service cree la interfaz IRecetaService con su codificación necesaria para el funcionamiento del proyecto.

**Comment by cristianortega0** [comment]
Realizado en la Rama Receta
